name: altsome_app
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  expandable_page_view: ^1.0.17
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.5.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  email_validator: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

  assets:
    - assets/images/avatar_logo.png
    - assets/images/indicator_image.png
    - assets/images/bit_coin.png
    - assets/images/toggle_view_graph.png
    - assets/images/sectors_logo.png
    - assets/images/404.png
    - assets/images/header.jpg

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Medium.ttf
