// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6-gVAzNDxnkymQd45aP89OXd9KwoP-AQ',
    appId: '1:501963981540:web:c46d53af51825e9859e2f1',
    messagingSenderId: '501963981540',
    projectId: 'check-db-a09a7',
    authDomain: 'check-db-a09a7.firebaseapp.com',
    storageBucket: 'check-db-a09a7.appspot.com',
    measurementId: 'G-S1M39GV3RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NdGN7YmMuiNsq3E6DySjlAxf4IhLfnw',
    appId: '1:501963981540:android:1f64776136e0f5fd59e2f1',
    messagingSenderId: '501963981540',
    projectId: 'check-db-a09a7',
    storageBucket: 'check-db-a09a7.appspot.com',
  );

}